import { createHash } from "node:crypto";
import { createWriteStream, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { CorpusRecord } from "../normalize/index.js";
import type { InventoryEntry } from "../sanitize/inventory.js";
import { buildManifest, type Manifest } from "./manifest.js";
import { stableStringify } from "./stable-stringify.js";

export * from "./manifest.js";

const DEFAULT_POLICY_YAML = `# trace-grab default policy — deny-by-default (ADR-0005)
# Applied when no tracegrab.yaml was supplied.
schema: trace-corpus-v1
defaults:
  strings: tokenize
  numbers: pass
  booleans: pass
  timestamps: pass
  keys: pass
pass_verbatim:
  - name
  - kind
  - status
  - error.kind
  - labels[].key
  - labels[].value
  - source.vendor
# No reveals, no drops, no time shift
reveals: []
drops: []
time: absolute
`;

const PASS_VERBATIM_INVENTORY = [
  "name",
  "kind",
  "status",
  "error.kind",
  "start",
  "end",
  "labels[].key",
  "labels[].value",
  "source.vendor",
];

/** Report header: title, generator/version/timestamp, source vendor. */
function renderHeader(manifest: Manifest): string {
  return [
    "# trace-grab corpus report",
    "",
    `Generated by ${manifest.generator.name} v${manifest.generator.version} at ${manifest.generated_at}.`,
    `Source vendor: ${manifest.source.vendor}.`,
  ].join("\n");
}

/**
 * Section 1 — the leak surface (ADR-0009). Revealed fields get top billing with counts and real
 * example values. With zero config there are no reveals, so the section falls back to the built-in
 * pass-verbatim set and a one-sentence statement a non-engineer can act on (issue #9 AC #1).
 */
function renderPlaintextSection(inventory: InventoryEntry[]): string {
  const revealed = inventory.filter((entry) => entry.disposition === "reveal");
  if (revealed.length > 0) {
    return [
      "## Plaintext fields",
      "",
      `These ${revealed.length} field(s) were explicitly revealed by your policy and leave your environment in plaintext:`,
      "",
      ...revealed.map(
        (entry) =>
          `- \`${entry.path}\` — ${entry.occurrences} occurrence(s), example: \`${(entry.example ?? "").replace(/\r?\n/g, " ")}\``,
      ),
      "",
      "Tool and span names, status, and typed fields (numbers, booleans, timestamps) also pass verbatim by default — see the path inventory below.",
    ].join("\n");
  }
  return [
    "## Plaintext fields",
    "",
    "With no policy file, only tool and span names, status, and typed fields (numbers, booleans, timestamps) leave your environment in plaintext. Every string value — including all ids — was tokenized.",
    "",
    "Built-in pass-verbatim fields:",
    "",
    ...PASS_VERBATIM_INVENTORY.map((field) => `- \`${field}\``),
  ].join("\n");
}

/**
 * Section 2 — warnings (ADR-0009). Unmatched policy rules render prominently under a `## Warnings`
 * heading, never as a footnote (issue #9 AC #2). Also surfaces dangling parents, excluded traces,
 * and capped inventories. The section is always present so an empty corpus still renders fully.
 */
function renderWarningsSection(manifest: Manifest, inventory: InventoryEntry[]): string {
  const warnings: string[] = [];
  for (const rule of manifest.warnings) {
    warnings.push(`- **Unmatched policy rule** — ${rule}`);
  }
  if (manifest.counts.dangling_parents > 0) {
    warnings.push(
      `- ${manifest.counts.dangling_parents} span(s) reference a parent_id absent from this corpus (dangling parents).`,
    );
  }
  if (manifest.counts.excluded_traces > 0) {
    warnings.push(
      `- ${manifest.counts.excluded_traces} trace(s) were excluded (by window: ${manifest.counts.excluded_by_window}, by limit: ${manifest.counts.excluded_by_limit}) and are not in this bundle.`,
    );
  }
  for (const entry of inventory.filter((e) => e.capped)) {
    warnings.push(
      `- Path \`${entry.path}\` hit the distinct-value cap; some distinct values are not counted in the table.`,
    );
  }
  const body =
    warnings.length > 0
      ? warnings.join("\n")
      : "No warnings: every policy rule matched a path, no dangling parents, no excluded traces, no capped inventories.";
  return ["## Warnings", "", body].join("\n");
}

/**
 * Section 3 — the full path inventory. One row per `InventoryEntry` (sorted, as `entries()`
 * returns): path · count · disposition · distinct values · example. Newlines collapse to spaces
 * and pipes are escaped so a value can't break the table row. An empty inventory (zero-record
 * corpus) renders an empty table with a placeholder rather than crashing (issue #9 AC #3).
 */
function renderInventorySection(inventory: InventoryEntry[]): string {
  const rows = inventory.map((entry) => {
    const path = entry.path.replace(/\r?\n/g, " ").replace(/\|/g, "\\|");
    const example =
      entry.example === null
        ? "—"
        : `\`${entry.example.replace(/\r?\n/g, " ").replace(/\|/g, "\\|")}\``;
    const distinct = `${entry.distinctValues}${entry.capped ? "+" : ""}`;
    return `| \`${path}\` | ${entry.occurrences} | ${entry.disposition} | ${distinct} | ${example} |`;
  });
  return [
    "## Path inventory",
    "",
    "One row per dotted path the sanitization walk visited. `[*]` collapses array elements; `distinct` is bounded by the cap (`+` means the path hit it, so some distinct values are not counted).",
    "",
    "| Path | Count | Disposition | Distinct | Example |",
    "| --- | ---: | --- | ---: | --- |",
    ...(rows.length > 0 ? rows : ["| _No paths — zero-record corpus._ | | | | |"]),
  ].join("\n");
}

/** Section 4 — counts and integrity: records, traces, distinct paths/tokens, exclusions, corpus and policy hashes. */
function renderCountsSection(manifest: Manifest): string {
  const c = manifest.counts;
  return [
    "## Counts and integrity",
    "",
    `- Records: ${c.records}`,
    `- Traces: ${c.traces}`,
    `- Distinct dotted paths: ${c.distinct_paths}`,
    `- Distinct tokens: ${c.distinct_tokens}`,
    `- Dangling parents: ${c.dangling_parents}`,
    `- Excluded traces: ${c.excluded_traces} (by window: ${c.excluded_by_window}, by limit: ${c.excluded_by_limit})`,
    `- Corpus SHA-256: \`${manifest.corpus_sha256}\``,
    `- Policy hash: \`${manifest.policy_hash}\``,
  ].join("\n");
}

/**
 * Section 5 — transfer instructions. Documentation, not built-in behaviour (PRD §6: "Transfer is
 * documented, not built"). A non-engineer can copy these and fill in the presigned URL.
 */
function renderTransferSection(): string {
  return [
    "## Transfer",
    "",
    "Archive and upload the bundle. These commands are documentation, not part of trace-grab — copy them and fill in the presigned URL your partner contact gives you.",
    "",
    "1. Archive the bundle directory:",
    "```",
    "tar -czf corpus.tar.gz -C <bundle-dir> .",
    "```",
    "2. Upload the archive to the presigned URL:",
    "```",
    "curl -T corpus.tar.gz https://upload.example.net/PLACEHOLDER",
    "```",
  ].join("\n");
}

/**
 * Section 6 — keymap and salt. Names both paths and states plainly that they were NOT included in
 * the bundle; they live in the partner's working directory under `.trace-grab/` (ADR-0006).
 */
function renderKeymapSection(): string {
  return [
    "## Keymap and salt",
    "",
    "The local reverse keymap (`.trace-grab/keymap.jsonl`) and the partner salt (`.trace-grab/salt`) were NOT included in this bundle. They live in your working directory under `.trace-grab/`, never inside the bundle. Back them up — losing the salt breaks cross-batch token correlation (ADR-0006).",
  ].join("\n");
}

/**
 * Renders `report.md` — a pure `(manifest, inventory) -> string` transform, no I/O. Sections, in
 * order: header, (1) plaintext/reveal, (2) warnings, (3) path inventory table, (4) counts and
 * integrity, (5) transfer instructions, (6) keymap and salt note (issue #9).
 */
export function renderReport(manifest: Manifest, inventory: InventoryEntry[]): string {
  return [
    renderHeader(manifest),
    renderPlaintextSection(inventory),
    renderWarningsSection(manifest, inventory),
    renderInventorySection(inventory),
    renderCountsSection(manifest),
    renderTransferSection(),
    renderKeymapSection(),
  ].join("\n\n") + "\n";
}

/**
 * Streams `corpus.jsonl` one record at a time, feeding each line into a running
 * SHA-256 hash. Never holds the full corpus in memory — each record is serialized,
 * hashed, and written before the next is touched. After streaming, writes
 * `manifest.json`, `policy.yaml` (the effective policy — user's `tracegrab.yaml`
 * verbatim, or the materialized default), and `report.md` (structural skeleton —
 * full rendering is issue #9). `excludedByLimit` and `excludedByWindow` carry the
 * whole-trace exclusion counts from limiting (ADR-0011) into the manifest.
 */
export interface BundleOptions {
  /** The effective policy YAML to write as `policy.yaml`. Defaults to the built-in policy. */
  policyYaml?: string;
  /** SHA-256 of the effective policy. Defaults to the built-in descriptor hash. */
  policyHash?: string;
  /** Warnings to surface in the manifest (unmatched-rule warnings from the resolver). */
  warnings?: string[];
  /** Path inventory snapshot (`PathInventory.entries()`) — feeds the report's inventory table. */
  inventory?: InventoryEntry[];
}

export async function writeBundle(
  outDir: string,
  records: CorpusRecord[],
  excludedByLimit = 0,
  excludedByWindow = 0,
  options?: BundleOptions,
): Promise<void> {
  mkdirSync(outDir, { recursive: true });

  const corpusPath = join(outDir, "corpus.jsonl");
  const stream = createWriteStream(corpusPath, { encoding: "utf8" });
  const hash = createHash("sha256");

  for (const record of records) {
    const bytes = Buffer.from(`${stableStringify(record)}\n`, "utf8");
    hash.update(bytes);
    if (!stream.write(bytes)) {
      // Backpressure: wait for the stream to drain before the next record so the
      // internal buffer never grows unboundedly (bounded memory over 500k records).
      await new Promise<void>((resolve) => stream.once("drain", resolve));
    }
  }

  await new Promise<void>((resolve, reject) => {
    stream.once("finish", () => resolve());
    stream.once("error", reject);
    stream.end();
  });

  const corpusHash = hash.digest("hex");
  const manifest = buildManifest(
    records,
    corpusHash,
    excludedByLimit,
    excludedByWindow,
    options?.policyHash,
    options?.warnings,
  );
  writeFileSync(join(outDir, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  writeFileSync(join(outDir, "policy.yaml"), options?.policyYaml ?? DEFAULT_POLICY_YAML);
  writeFileSync(join(outDir, "report.md"), renderReport(manifest, options?.inventory ?? []));
}
