import { createHash } from "node:crypto";
import { createWriteStream, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { CorpusRecord } from "../normalize/index.js";
import type { InventoryEntry } from "../sanitize/inventory.js";
import { buildManifest, type Manifest } from "./manifest.js";
import { stableStringify } from "./stable-stringify.js";

export * from "./manifest.js";

const DEFAULT_POLICY_YAML = `# trace-grab default policy — deny-by-default (ADR-0005)
# Applied when no tracegrab.yaml was supplied.
schema: trace-corpus-v1
defaults:
  strings: tokenize
  numbers: pass
  booleans: pass
  timestamps: pass
  keys: pass
pass_verbatim:
  - name
  - kind
  - status
  - error.kind
  - labels[].key
  - labels[].value
  - source.vendor
# No reveals, no drops, no time shift
reveals: []
drops: []
time: absolute
`;

const PASS_VERBATIM_INVENTORY = [
  "name",
  "kind",
  "status",
  "error.kind",
  "start",
  "end",
  "labels[].key",
  "labels[].value",
  "source.vendor",
];

function renderReport(manifest: Manifest, inventory: InventoryEntry[]): string {
  const lines: string[] = [
    `# trace-grab corpus report`,
    ``,
    `Generated by ${manifest.generator.name} v${manifest.generator.version} at ${manifest.generated_at}.`,
    ``,
    `## Corpus summary`,
    ``,
    `- Traces: ${manifest.counts.traces}`,
    `- Records: ${manifest.counts.records}`,
    `- Distinct dotted paths: ${manifest.counts.distinct_paths}`,
    `- Distinct tokens: ${manifest.counts.distinct_tokens}`,
    `- Dangling parents: ${manifest.counts.dangling_parents}`,
    `- Excluded traces: ${manifest.counts.excluded_traces} (by window: ${manifest.counts.excluded_by_window}, by limit: ${manifest.counts.excluded_by_limit})`,
    ``,
    `## Pass-verbatim field inventory`,
    ``,
    `The bounded list from SCHEMA.md's disposition table — these fields survive sanitization unchanged:`,
    ``,
    ...PASS_VERBATIM_INVENTORY.map((field) => `- ${field}`),
    ``,
    `> Full report rendering is issue #9.`,
    ``,
  ];
  return `${lines.join("\n")}\n`;
}

/**
 * Streams `corpus.jsonl` one record at a time, feeding each line into a running
 * SHA-256 hash. Never holds the full corpus in memory — each record is serialized,
 * hashed, and written before the next is touched. After streaming, writes
 * `manifest.json`, `policy.yaml` (the effective policy — user's `tracegrab.yaml`
 * verbatim, or the materialized default), and `report.md` (structural skeleton —
 * full rendering is issue #9). `excludedByLimit` and `excludedByWindow` carry the
 * whole-trace exclusion counts from limiting (ADR-0011) into the manifest.
 */
export interface BundleOptions {
  /** The effective policy YAML to write as `policy.yaml`. Defaults to the built-in policy. */
  policyYaml?: string;
  /** SHA-256 of the effective policy. Defaults to the built-in descriptor hash. */
  policyHash?: string;
  /** Warnings to surface in the manifest (unmatched-rule warnings from the resolver). */
  warnings?: string[];
  /** Path inventory snapshot (`PathInventory.entries()`) — feeds the report's inventory table. */
  inventory?: InventoryEntry[];
}

export async function writeBundle(
  outDir: string,
  records: CorpusRecord[],
  excludedByLimit = 0,
  excludedByWindow = 0,
  options?: BundleOptions,
): Promise<void> {
  mkdirSync(outDir, { recursive: true });

  const corpusPath = join(outDir, "corpus.jsonl");
  const stream = createWriteStream(corpusPath, { encoding: "utf8" });
  const hash = createHash("sha256");

  for (const record of records) {
    const bytes = Buffer.from(`${stableStringify(record)}\n`, "utf8");
    hash.update(bytes);
    if (!stream.write(bytes)) {
      // Backpressure: wait for the stream to drain before the next record so the
      // internal buffer never grows unboundedly (bounded memory over 500k records).
      await new Promise<void>((resolve) => stream.once("drain", resolve));
    }
  }

  await new Promise<void>((resolve, reject) => {
    stream.once("finish", () => resolve());
    stream.once("error", reject);
    stream.end();
  });

  const corpusHash = hash.digest("hex");
  const manifest = buildManifest(
    records,
    corpusHash,
    excludedByLimit,
    excludedByWindow,
    options?.policyHash,
    options?.warnings,
  );
  writeFileSync(join(outDir, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  writeFileSync(join(outDir, "policy.yaml"), options?.policyYaml ?? DEFAULT_POLICY_YAML);
  writeFileSync(join(outDir, "report.md"), renderReport(manifest, options?.inventory ?? []));
}
